var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/app.ts
import express from "express";
import cors from "cors";
import { toNodeHandler } from "better-auth/node";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// src/generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// src/generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.0",
  "engineVersion": "ab56fe763f921d033a6c195e7ddeb3e255bdbb57",
  "activeProvider": "postgresql",
  "inlineSchema": '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../src/generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nenum Role {\n  Student\n  Tutor\n  Admin\n}\n\nmodel User {\n  id            String        @id @default(cuid())\n  name          String?\n  email         String\n  emailVerified Boolean       @default(false)\n  image         String?\n  createdAt     DateTime      @default(now())\n  updatedAt     DateTime      @updatedAt\n  sessions      Session[]\n  accounts      Account[]\n  tutorProfile  TutorProfile?\n  bookings      Booking[]     @relation("StudentBookings")\n  reviews       Review[]\n  status        String        @default("active")\n\n  role Role? @default(Student)\n\n  banned     Boolean?  @default(false)\n  banReason  String?\n  banExpires DateTime?\n\n  @@unique([email])\n  @@map("user")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  impersonatedBy String?\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n\nmodel Category {\n  id          String         @id @default(uuid())\n  name        String         @unique\n  description String?\n  tutors      TutorProfile[]\n}\n\nenum BookingStatus {\n  PENDING\n  CONFIRMED\n  COMPLETED\n  CANCELLED\n}\n\nmodel Booking {\n  id          String        @id @default(uuid())\n  sessionDate DateTime\n  startTime   DateTime\n  endTime     DateTime\n  status      BookingStatus @default(CONFIRMED)\n  price       Float\n  student     User          @relation("StudentBookings", fields: [studentId], references: [id], onDelete: Cascade)\n  studentId   String\n  tutor       TutorProfile  @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  tutorId     String\n  //reviwe need to add\n}\n\nmodel Review {\n  id        String       @id @default(uuid())\n  rating    Int\n  comment   String?\n  createdAt DateTime     @default(now())\n  student   User         @relation(fields: [studentId], references: [id], onDelete: Cascade)\n  studentId String\n  tutor     TutorProfile @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  tutorId   String\n}\n\nmodel TutorProfile {\n  id   String  @id @default(uuid())\n  name String\n  bio  String?\n\n  experience   String?\n  hourlyRate   Float?\n  availability Json?\n  rating       Float     @default(0)\n  user         User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  userId       String    @unique\n  category     Category? @relation(fields: [categoryId], references: [id], onDelete: Cascade)\n  categoryId   String?\n\n  bookings Booking[]\n  reviews  Review[]\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"bookings","kind":"object","type":"Booking","relationName":"StudentBookings"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"status","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"banned","kind":"scalar","type":"Boolean"},{"name":"banReason","kind":"scalar","type":"String"},{"name":"banExpires","kind":"scalar","type":"DateTime"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"},{"name":"impersonatedBy","kind":"scalar","type":"String"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"tutors","kind":"object","type":"TutorProfile","relationName":"CategoryToTutorProfile"}],"dbName":null},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"sessionDate","kind":"scalar","type":"DateTime"},{"name":"startTime","kind":"scalar","type":"DateTime"},{"name":"endTime","kind":"scalar","type":"DateTime"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"price","kind":"scalar","type":"Float"},{"name":"student","kind":"object","type":"User","relationName":"StudentBookings"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"BookingToTutorProfile"},{"name":"tutorId","kind":"scalar","type":"String"}],"dbName":null},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"student","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"ReviewToTutorProfile"},{"name":"tutorId","kind":"scalar","type":"String"}],"dbName":null},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"experience","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Float"},{"name":"availability","kind":"scalar","type":"Json"},{"name":"rating","kind":"scalar","type":"Float"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"},{"name":"userId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToTutorProfile"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToTutorProfile"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToTutorProfile"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","tutors","_count","category","student","tutor","bookings","reviews","tutorProfile","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","_avg","_sum","Booking.groupBy","Booking.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","TutorProfile.groupBy","TutorProfile.aggregate","AND","OR","NOT","id","name","bio","experience","hourlyRate","availability","rating","userId","categoryId","equals","in","notIn","lt","lte","gt","gte","not","string_contains","string_starts_with","string_ends_with","array_starts_with","array_ends_with","array_contains","contains","startsWith","endsWith","comment","createdAt","studentId","tutorId","sessionDate","startTime","endTime","BookingStatus","status","price","description","every","some","none","identifier","value","expiresAt","updatedAt","accountId","providerId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","impersonatedBy","email","emailVerified","image","Role","role","banned","banReason","banExpires","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "9wNKgAEUBAAAkgIAIAUAAJMCACALAACVAgAgDAAAlgIAIA0AAJQCACCWAQAAjQIAMJcBAAAkABCYAQAAjQIAMJkBAQAAAAGaAQEA-AEAIbQBQAD9AQAhuwEBAPwBACHEAUAA_QEAIdIBAQAAAAHTASAAjgIAIdQBAQD4AQAh1gEAAI8C1gEj1wEgAJACACHYAQEA-AEAIdkBQACRAgAhAQAAAAEAIA0DAACZAgAglgEAAKMCADCXAQAAAwAQmAEAAKMCADCZAQEA_AEAIaABAQD8AQAhtAFAAP0BACHDAUAA_QEAIcQBQAD9AQAhzgEBAPwBACHPAQEA-AEAIdABAQD4AQAh0QEBAPgBACEEAwAAxwMAIM8BAACkAgAg0AEAAKQCACDRAQAApAIAIA0DAACZAgAglgEAAKMCADCXAQAAAwAQmAEAAKMCADCZAQEAAAABoAEBAPwBACG0AUAA_QEAIcMBQAD9AQAhxAFAAP0BACHOAQEAAAABzwEBAPgBACHQAQEA-AEAIdEBAQD4AQAhAwAAAAMAIAEAAAQAMAIAAAUAIBEDAACZAgAglgEAAKICADCXAQAABwAQmAEAAKICADCZAQEA_AEAIaABAQD8AQAhtAFAAP0BACHEAUAA_QEAIcUBAQD8AQAhxgEBAPwBACHHAQEA-AEAIcgBAQD4AQAhyQEBAPgBACHKAUAAkQIAIcsBQACRAgAhzAEBAPgBACHNAQEA-AEAIQgDAADHAwAgxwEAAKQCACDIAQAApAIAIMkBAACkAgAgygEAAKQCACDLAQAApAIAIMwBAACkAgAgzQEAAKQCACARAwAAmQIAIJYBAACiAgAwlwEAAAcAEJgBAACiAgAwmQEBAAAAAaABAQD8AQAhtAFAAP0BACHEAUAA_QEAIcUBAQD8AQAhxgEBAPwBACHHAQEA-AEAIcgBAQD4AQAhyQEBAPgBACHKAUAAkQIAIcsBQACRAgAhzAEBAPgBACHNAQEA-AEAIQMAAAAHACABAAAIADACAAAJACAQAwAAmQIAIAgAAKECACALAACVAgAgDAAAlgIAIJYBAACeAgAwlwEAAAsAEJgBAACeAgAwmQEBAPwBACGaAQEA_AEAIZsBAQD4AQAhnAEBAPgBACGdAQgAnwIAIZ4BAACgAgAgnwEIAJ0CACGgAQEA_AEAIaEBAQD4AQAhAQAAAAsAIAcGAAD5AQAglgEAAPcBADCXAQAADQAQmAEAAPcBADCZAQEA_AEAIZoBAQD8AQAhvQEBAPgBACEBAAAADQAgCQMAAMcDACAIAADIAwAgCwAAxQMAIAwAAMYDACCbAQAApAIAIJwBAACkAgAgnQEAAKQCACCeAQAApAIAIKEBAACkAgAgEAMAAJkCACAIAAChAgAgCwAAlQIAIAwAAJYCACCWAQAAngIAMJcBAAALABCYAQAAngIAMJkBAQAAAAGaAQEA_AEAIZsBAQD4AQAhnAEBAPgBACGdAQgAnwIAIZ4BAACgAgAgnwEIAJ0CACGgAQEAAAABoQEBAPgBACEDAAAACwAgAQAADwAwAgAAEAAgAQAAAAsAIA0JAACZAgAgCgAAmgIAIJYBAACbAgAwlwEAABMAEJgBAACbAgAwmQEBAPwBACG1AQEA_AEAIbYBAQD8AQAhtwFAAP0BACG4AUAA_QEAIbkBQAD9AQAhuwEAAJwCuwEivAEIAJ0CACECCQAAxwMAIAoAAMQDACANCQAAmQIAIAoAAJoCACCWAQAAmwIAMJcBAAATABCYAQAAmwIAMJkBAQAAAAG1AQEA_AEAIbYBAQD8AQAhtwFAAP0BACG4AUAA_QEAIbkBQAD9AQAhuwEAAJwCuwEivAEIAJ0CACEDAAAAEwAgAQAAFAAwAgAAFQAgCwkAAJkCACAKAACaAgAglgEAAJcCADCXAQAAFwAQmAEAAJcCADCZAQEA_AEAIZ8BAgCYAgAhswEBAPgBACG0AUAA_QEAIbUBAQD8AQAhtgEBAPwBACEDCQAAxwMAIAoAAMQDACCzAQAApAIAIAsJAACZAgAgCgAAmgIAIJYBAACXAgAwlwEAABcAEJgBAACXAgAwmQEBAAAAAZ8BAgCYAgAhswEBAPgBACG0AUAA_QEAIbUBAQD8AQAhtgEBAPwBACEDAAAAFwAgAQAAGAAwAgAAGQAgAQAAABMAIAEAAAAXACADAAAAEwAgAQAAFAAwAgAAFQAgAwAAABcAIAEAABgAMAIAABkAIAEAAAADACABAAAABwAgAQAAABMAIAEAAAAXACABAAAAAQAgFAQAAJICACAFAACTAgAgCwAAlQIAIAwAAJYCACANAACUAgAglgEAAI0CADCXAQAAJAAQmAEAAI0CADCZAQEA_AEAIZoBAQD4AQAhtAFAAP0BACG7AQEA_AEAIcQBQAD9AQAh0gEBAPwBACHTASAAjgIAIdQBAQD4AQAh1gEAAI8C1gEj1wEgAJACACHYAQEA-AEAIdkBQACRAgAhCwQAAMIDACAFAADDAwAgCwAAxQMAIAwAAMYDACANAADEAwAgmgEAAKQCACDUAQAApAIAINYBAACkAgAg1wEAAKQCACDYAQAApAIAINkBAACkAgAgAwAAACQAIAEAACUAMAIAAAEAIAMAAAAkACABAAAlADACAAABACADAAAAJAAgAQAAJQAwAgAAAQAgEQQAAL0DACAFAAC-AwAgCwAAwAMAIAwAAMEDACANAAC_AwAgmQEBAAAAAZoBAQAAAAG0AUAAAAABuwEBAAAAAcQBQAAAAAHSAQEAAAAB0wEgAAAAAdQBAQAAAAHWAQAAANYBA9cBIAAAAAHYAQEAAAAB2QFAAAAAAQETAAApACAMmQEBAAAAAZoBAQAAAAG0AUAAAAABuwEBAAAAAcQBQAAAAAHSAQEAAAAB0wEgAAAAAdQBAQAAAAHWAQAAANYBA9cBIAAAAAHYAQEAAAAB2QFAAAAAAQETAAArADABEwAAKwAwEQQAAIkDACAFAACKAwAgCwAAjAMAIAwAAI0DACANAACLAwAgmQEBAKoCACGaAQEAqwIAIbQBQAC9AgAhuwEBAKoCACHEAUAAvQIAIdIBAQCqAgAh0wEgAIYDACHUAQEAqwIAIdYBAACHA9YBI9cBIACIAwAh2AEBAKsCACHZAUAA-wIAIQIAAAABACATAAAuACAMmQEBAKoCACGaAQEAqwIAIbQBQAC9AgAhuwEBAKoCACHEAUAAvQIAIdIBAQCqAgAh0wEgAIYDACHUAQEAqwIAIdYBAACHA9YBI9cBIACIAwAh2AEBAKsCACHZAUAA-wIAIQIAAAAkACATAAAwACACAAAAJAAgEwAAMAAgAwAAAAEAIBoAACkAIBsAAC4AIAEAAAABACABAAAAJAAgCQcAAIMDACAgAACFAwAgIQAAhAMAIJoBAACkAgAg1AEAAKQCACDWAQAApAIAINcBAACkAgAg2AEAAKQCACDZAQAApAIAIA-WAQAAgwIAMJcBAAA3ABCYAQAAgwIAMJkBAQDcAQAhmgEBAN0BACG0AUAA7gEAIbsBAQDcAQAhxAFAAO4BACHSAQEA3AEAIdMBIACEAgAh1AEBAN0BACHWAQAAhQLWASPXASAAhgIAIdgBAQDdAQAh2QFAAP8BACEDAAAAJAAgAQAANgAwHwAANwAgAwAAACQAIAEAACUAMAIAAAEAIAEAAAAFACABAAAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgCgMAAIIDACCZAQEAAAABoAEBAAAAAbQBQAAAAAHDAUAAAAABxAFAAAAAAc4BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAEBEwAAPwAgCZkBAQAAAAGgAQEAAAABtAFAAAAAAcMBQAAAAAHEAUAAAAABzgEBAAAAAc8BAQAAAAHQAQEAAAAB0QEBAAAAAQETAABBADABEwAAQQAwCgMAAIEDACCZAQEAqgIAIaABAQCqAgAhtAFAAL0CACHDAUAAvQIAIcQBQAC9AgAhzgEBAKoCACHPAQEAqwIAIdABAQCrAgAh0QEBAKsCACECAAAABQAgEwAARAAgCZkBAQCqAgAhoAEBAKoCACG0AUAAvQIAIcMBQAC9AgAhxAFAAL0CACHOAQEAqgIAIc8BAQCrAgAh0AEBAKsCACHRAQEAqwIAIQIAAAADACATAABGACACAAAAAwAgEwAARgAgAwAAAAUAIBoAAD8AIBsAAEQAIAEAAAAFACABAAAAAwAgBgcAAP4CACAgAACAAwAgIQAA_wIAIM8BAACkAgAg0AEAAKQCACDRAQAApAIAIAyWAQAAggIAMJcBAABNABCYAQAAggIAMJkBAQDcAQAhoAEBANwBACG0AUAA7gEAIcMBQADuAQAhxAFAAO4BACHOAQEA3AEAIc8BAQDdAQAh0AEBAN0BACHRAQEA3QEAIQMAAAADACABAABMADAfAABNACADAAAAAwAgAQAABAAwAgAABQAgAQAAAAkAIAEAAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACAOAwAA_QIAIJkBAQAAAAGgAQEAAAABtAFAAAAAAcQBQAAAAAHFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAAAAAcoBQAAAAAHLAUAAAAABzAEBAAAAAc0BAQAAAAEBEwAAVQAgDZkBAQAAAAGgAQEAAAABtAFAAAAAAcQBQAAAAAHFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAAAAAcoBQAAAAAHLAUAAAAABzAEBAAAAAc0BAQAAAAEBEwAAVwAwARMAAFcAMA4DAAD8AgAgmQEBAKoCACGgAQEAqgIAIbQBQAC9AgAhxAFAAL0CACHFAQEAqgIAIcYBAQCqAgAhxwEBAKsCACHIAQEAqwIAIckBAQCrAgAhygFAAPsCACHLAUAA-wIAIcwBAQCrAgAhzQEBAKsCACECAAAACQAgEwAAWgAgDZkBAQCqAgAhoAEBAKoCACG0AUAAvQIAIcQBQAC9AgAhxQEBAKoCACHGAQEAqgIAIccBAQCrAgAhyAEBAKsCACHJAQEAqwIAIcoBQAD7AgAhywFAAPsCACHMAQEAqwIAIc0BAQCrAgAhAgAAAAcAIBMAAFwAIAIAAAAHACATAABcACADAAAACQAgGgAAVQAgGwAAWgAgAQAAAAkAIAEAAAAHACAKBwAA-AIAICAAAPoCACAhAAD5AgAgxwEAAKQCACDIAQAApAIAIMkBAACkAgAgygEAAKQCACDLAQAApAIAIMwBAACkAgAgzQEAAKQCACAQlgEAAP4BADCXAQAAYwAQmAEAAP4BADCZAQEA3AEAIaABAQDcAQAhtAFAAO4BACHEAUAA7gEAIcUBAQDcAQAhxgEBANwBACHHAQEA3QEAIcgBAQDdAQAhyQEBAN0BACHKAUAA_wEAIcsBQAD_AQAhzAEBAN0BACHNAQEA3QEAIQMAAAAHACABAABiADAfAABjACADAAAABwAgAQAACAAwAgAACQAgCZYBAAD7AQAwlwEAAGkAEJgBAAD7AQAwmQEBAAAAAbQBQAD9AQAhwQEBAPwBACHCAQEA_AEAIcMBQAD9AQAhxAFAAP0BACEBAAAAZgAgAQAAAGYAIAmWAQAA-wEAMJcBAABpABCYAQAA-wEAMJkBAQD8AQAhtAFAAP0BACHBAQEA_AEAIcIBAQD8AQAhwwFAAP0BACHEAUAA_QEAIQADAAAAaQAgAQAAagAwAgAAZgAgAwAAAGkAIAEAAGoAMAIAAGYAIAMAAABpACABAABqADACAABmACAGmQEBAAAAAbQBQAAAAAHBAQEAAAABwgEBAAAAAcMBQAAAAAHEAUAAAAABARMAAG4AIAaZAQEAAAABtAFAAAAAAcEBAQAAAAHCAQEAAAABwwFAAAAAAcQBQAAAAAEBEwAAcAAwARMAAHAAMAaZAQEAqgIAIbQBQAC9AgAhwQEBAKoCACHCAQEAqgIAIcMBQAC9AgAhxAFAAL0CACECAAAAZgAgEwAAcwAgBpkBAQCqAgAhtAFAAL0CACHBAQEAqgIAIcIBAQCqAgAhwwFAAL0CACHEAUAAvQIAIQIAAABpACATAAB1ACACAAAAaQAgEwAAdQAgAwAAAGYAIBoAAG4AIBsAAHMAIAEAAABmACABAAAAaQAgAwcAAPUCACAgAAD3AgAgIQAA9gIAIAmWAQAA-gEAMJcBAAB8ABCYAQAA-gEAMJkBAQDcAQAhtAFAAO4BACHBAQEA3AEAIcIBAQDcAQAhwwFAAO4BACHEAUAA7gEAIQMAAABpACABAAB7ADAfAAB8ACADAAAAaQAgAQAAagAwAgAAZgAgBwYAAPkBACCWAQAA9wEAMJcBAAANABCYAQAA9wEAMJkBAQAAAAGaAQEAAAABvQEBAPgBACEBAAAAfwAgAQAAAH8AIAIGAAD0AgAgvQEAAKQCACADAAAADQAgAQAAggEAMAIAAH8AIAMAAAANACABAACCAQAwAgAAfwAgAwAAAA0AIAEAAIIBADACAAB_ACAEBgAA8wIAIJkBAQAAAAGaAQEAAAABvQEBAAAAAQETAACGAQAgA5kBAQAAAAGaAQEAAAABvQEBAAAAAQETAACIAQAwARMAAIgBADAEBgAA5gIAIJkBAQCqAgAhmgEBAKoCACG9AQEAqwIAIQIAAAB_ACATAACLAQAgA5kBAQCqAgAhmgEBAKoCACG9AQEAqwIAIQIAAAANACATAACNAQAgAgAAAA0AIBMAAI0BACADAAAAfwAgGgAAhgEAIBsAAIsBACABAAAAfwAgAQAAAA0AIAQHAADjAgAgIAAA5QIAICEAAOQCACC9AQAApAIAIAaWAQAA9gEAMJcBAACUAQAQmAEAAPYBADCZAQEA3AEAIZoBAQDcAQAhvQEBAN0BACEDAAAADQAgAQAAkwEAMB8AAJQBACADAAAADQAgAQAAggEAMAIAAH8AIAEAAAAVACABAAAAFQAgAwAAABMAIAEAABQAMAIAABUAIAMAAAATACABAAAUADACAAAVACADAAAAEwAgAQAAFAAwAgAAFQAgCgkAANACACAKAADiAgAgmQEBAAAAAbUBAQAAAAG2AQEAAAABtwFAAAAAAbgBQAAAAAG5AUAAAAABuwEAAAC7AQK8AQgAAAABARMAAJwBACAImQEBAAAAAbUBAQAAAAG2AQEAAAABtwFAAAAAAbgBQAAAAAG5AUAAAAABuwEAAAC7AQK8AQgAAAABARMAAJ4BADABEwAAngEAMAoJAADOAgAgCgAA4QIAIJkBAQCqAgAhtQEBAKoCACG2AQEAqgIAIbcBQAC9AgAhuAFAAL0CACG5AUAAvQIAIbsBAADMArsBIrwBCACtAgAhAgAAABUAIBMAAKEBACAImQEBAKoCACG1AQEAqgIAIbYBAQCqAgAhtwFAAL0CACG4AUAAvQIAIbkBQAC9AgAhuwEAAMwCuwEivAEIAK0CACECAAAAEwAgEwAAowEAIAIAAAATACATAACjAQAgAwAAABUAIBoAAJwBACAbAAChAQAgAQAAABUAIAEAAAATACAFBwAA3AIAICAAAN8CACAhAADeAgAgcgAA3QIAIHMAAOACACALlgEAAPIBADCXAQAAqgEAEJgBAADyAQAwmQEBANwBACG1AQEA3AEAIbYBAQDcAQAhtwFAAO4BACG4AUAA7gEAIbkBQADuAQAhuwEAAPMBuwEivAEIAOABACEDAAAAEwAgAQAAqQEAMB8AAKoBACADAAAAEwAgAQAAFAAwAgAAFQAgAQAAABkAIAEAAAAZACADAAAAFwAgAQAAGAAwAgAAGQAgAwAAABcAIAEAABgAMAIAABkAIAMAAAAXACABAAAYADACAAAZACAICQAAwQIAIAoAANsCACCZAQEAAAABnwECAAAAAbMBAQAAAAG0AUAAAAABtQEBAAAAAbYBAQAAAAEBEwAAsgEAIAaZAQEAAAABnwECAAAAAbMBAQAAAAG0AUAAAAABtQEBAAAAAbYBAQAAAAEBEwAAtAEAMAETAAC0AQAwCAkAAL8CACAKAADaAgAgmQEBAKoCACGfAQIAvAIAIbMBAQCrAgAhtAFAAL0CACG1AQEAqgIAIbYBAQCqAgAhAgAAABkAIBMAALcBACAGmQEBAKoCACGfAQIAvAIAIbMBAQCrAgAhtAFAAL0CACG1AQEAqgIAIbYBAQCqAgAhAgAAABcAIBMAALkBACACAAAAFwAgEwAAuQEAIAMAAAAZACAaAACyAQAgGwAAtwEAIAEAAAAZACABAAAAFwAgBgcAANUCACAgAADYAgAgIQAA1wIAIHIAANYCACBzAADZAgAgswEAAKQCACAJlgEAAOwBADCXAQAAwAEAEJgBAADsAQAwmQEBANwBACGfAQIA7QEAIbMBAQDdAQAhtAFAAO4BACG1AQEA3AEAIbYBAQDcAQAhAwAAABcAIAEAAL8BADAfAADAAQAgAwAAABcAIAEAABgAMAIAABkAIAEAAAAQACABAAAAEAAgAwAAAAsAIAEAAA8AMAIAABAAIAMAAAALACABAAAPADACAAAQACADAAAACwAgAQAADwAwAgAAEAAgDQMAANECACAIAADSAgAgCwAA0wIAIAwAANQCACCZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BgAAAAAGfAQgAAAABoAEBAAAAAaEBAQAAAAEBEwAAyAEAIAmZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BgAAAAAGfAQgAAAABoAEBAAAAAaEBAQAAAAEBEwAAygEAMAETAADKAQAwAQAAAA0AIA0DAACuAgAgCAAArwIAIAsAALACACAMAACxAgAgmQEBAKoCACGaAQEAqgIAIZsBAQCrAgAhnAEBAKsCACGdAQgArAIAIZ4BgAAAAAGfAQgArQIAIaABAQCqAgAhoQEBAKsCACECAAAAEAAgEwAAzgEAIAmZAQEAqgIAIZoBAQCqAgAhmwEBAKsCACGcAQEAqwIAIZ0BCACsAgAhngGAAAAAAZ8BCACtAgAhoAEBAKoCACGhAQEAqwIAIQIAAAALACATAADQAQAgAgAAAAsAIBMAANABACABAAAADQAgAwAAABAAIBoAAMgBACAbAADOAQAgAQAAABAAIAEAAAALACAKBwAApQIAICAAAKgCACAhAACnAgAgcgAApgIAIHMAAKkCACCbAQAApAIAIJwBAACkAgAgnQEAAKQCACCeAQAApAIAIKEBAACkAgAgDJYBAADbAQAwlwEAANgBABCYAQAA2wEAMJkBAQDcAQAhmgEBANwBACGbAQEA3QEAIZwBAQDdAQAhnQEIAN4BACGeAQAA3wEAIJ8BCADgAQAhoAEBANwBACGhAQEA3QEAIQMAAAALACABAADXAQAwHwAA2AEAIAMAAAALACABAAAPADACAAAQACAMlgEAANsBADCXAQAA2AEAEJgBAADbAQAwmQEBANwBACGaAQEA3AEAIZsBAQDdAQAhnAEBAN0BACGdAQgA3gEAIZ4BAADfAQAgnwEIAOABACGgAQEA3AEAIaEBAQDdAQAhDgcAAOIBACAgAADrAQAgIQAA6wEAIKIBAQAAAAGjAQEAAAAEpAEBAAAABKUBAQAAAAGmAQEAAAABpwEBAAAAAagBAQAAAAGpAQEA6gEAIbABAQAAAAGxAQEAAAABsgEBAAAAAQ4HAADkAQAgIAAA6QEAICEAAOkBACCiAQEAAAABowEBAAAABaQBAQAAAAWlAQEAAAABpgEBAAAAAacBAQAAAAGoAQEAAAABqQEBAOgBACGwAQEAAAABsQEBAAAAAbIBAQAAAAENBwAA5AEAICAAAOcBACAhAADnAQAgcgAA5wEAIHMAAOcBACCiAQgAAAABowEIAAAABaQBCAAAAAWlAQgAAAABpgEIAAAAAacBCAAAAAGoAQgAAAABqQEIAOYBACEPBwAA5AEAICAAAOUBACAhAADlAQAgogGAAAAAAaUBgAAAAAGmAYAAAAABpwGAAAAAAagBgAAAAAGpAYAAAAABqgEBAAAAAasBAQAAAAGsAQEAAAABrQGAAAAAAa4BgAAAAAGvAYAAAAABDQcAAOIBACAgAADjAQAgIQAA4wEAIHIAAOMBACBzAADjAQAgogEIAAAAAaMBCAAAAASkAQgAAAAEpQEIAAAAAaYBCAAAAAGnAQgAAAABqAEIAAAAAakBCADhAQAhDQcAAOIBACAgAADjAQAgIQAA4wEAIHIAAOMBACBzAADjAQAgogEIAAAAAaMBCAAAAASkAQgAAAAEpQEIAAAAAaYBCAAAAAGnAQgAAAABqAEIAAAAAakBCADhAQAhCKIBAgAAAAGjAQIAAAAEpAECAAAABKUBAgAAAAGmAQIAAAABpwECAAAAAagBAgAAAAGpAQIA4gEAIQiiAQgAAAABowEIAAAABKQBCAAAAASlAQgAAAABpgEIAAAAAacBCAAAAAGoAQgAAAABqQEIAOMBACEIogECAAAAAaMBAgAAAAWkAQIAAAAFpQECAAAAAaYBAgAAAAGnAQIAAAABqAECAAAAAakBAgDkAQAhDKIBgAAAAAGlAYAAAAABpgGAAAAAAacBgAAAAAGoAYAAAAABqQGAAAAAAaoBAQAAAAGrAQEAAAABrAEBAAAAAa0BgAAAAAGuAYAAAAABrwGAAAAAAQ0HAADkAQAgIAAA5wEAICEAAOcBACByAADnAQAgcwAA5wEAIKIBCAAAAAGjAQgAAAAFpAEIAAAABaUBCAAAAAGmAQgAAAABpwEIAAAAAagBCAAAAAGpAQgA5gEAIQiiAQgAAAABowEIAAAABaQBCAAAAAWlAQgAAAABpgEIAAAAAacBCAAAAAGoAQgAAAABqQEIAOcBACEOBwAA5AEAICAAAOkBACAhAADpAQAgogEBAAAAAaMBAQAAAAWkAQEAAAAFpQEBAAAAAaYBAQAAAAGnAQEAAAABqAEBAAAAAakBAQDoAQAhsAEBAAAAAbEBAQAAAAGyAQEAAAABC6IBAQAAAAGjAQEAAAAFpAEBAAAABaUBAQAAAAGmAQEAAAABpwEBAAAAAagBAQAAAAGpAQEA6QEAIbABAQAAAAGxAQEAAAABsgEBAAAAAQ4HAADiAQAgIAAA6wEAICEAAOsBACCiAQEAAAABowEBAAAABKQBAQAAAASlAQEAAAABpgEBAAAAAacBAQAAAAGoAQEAAAABqQEBAOoBACGwAQEAAAABsQEBAAAAAbIBAQAAAAELogEBAAAAAaMBAQAAAASkAQEAAAAEpQEBAAAAAaYBAQAAAAGnAQEAAAABqAEBAAAAAakBAQDrAQAhsAEBAAAAAbEBAQAAAAGyAQEAAAABCZYBAADsAQAwlwEAAMABABCYAQAA7AEAMJkBAQDcAQAhnwECAO0BACGzAQEA3QEAIbQBQADuAQAhtQEBANwBACG2AQEA3AEAIQ0HAADiAQAgIAAA4gEAICEAAOIBACByAADjAQAgcwAA4gEAIKIBAgAAAAGjAQIAAAAEpAECAAAABKUBAgAAAAGmAQIAAAABpwECAAAAAagBAgAAAAGpAQIA8QEAIQsHAADiAQAgIAAA8AEAICEAAPABACCiAUAAAAABowFAAAAABKQBQAAAAASlAUAAAAABpgFAAAAAAacBQAAAAAGoAUAAAAABqQFAAO8BACELBwAA4gEAICAAAPABACAhAADwAQAgogFAAAAAAaMBQAAAAASkAUAAAAAEpQFAAAAAAaYBQAAAAAGnAUAAAAABqAFAAAAAAakBQADvAQAhCKIBQAAAAAGjAUAAAAAEpAFAAAAABKUBQAAAAAGmAUAAAAABpwFAAAAAAagBQAAAAAGpAUAA8AEAIQ0HAADiAQAgIAAA4gEAICEAAOIBACByAADjAQAgcwAA4gEAIKIBAgAAAAGjAQIAAAAEpAECAAAABKUBAgAAAAGmAQIAAAABpwECAAAAAagBAgAAAAGpAQIA8QEAIQuWAQAA8gEAMJcBAACqAQAQmAEAAPIBADCZAQEA3AEAIbUBAQDcAQAhtgEBANwBACG3AUAA7gEAIbgBQADuAQAhuQFAAO4BACG7AQAA8wG7ASK8AQgA4AEAIQcHAADiAQAgIAAA9QEAICEAAPUBACCiAQAAALsBAqMBAAAAuwEIpAEAAAC7AQipAQAA9AG7ASIHBwAA4gEAICAAAPUBACAhAAD1AQAgogEAAAC7AQKjAQAAALsBCKQBAAAAuwEIqQEAAPQBuwEiBKIBAAAAuwECowEAAAC7AQikAQAAALsBCKkBAAD1AbsBIgaWAQAA9gEAMJcBAACUAQAQmAEAAPYBADCZAQEA3AEAIZoBAQDcAQAhvQEBAN0BACEHBgAA-QEAIJYBAAD3AQAwlwEAAA0AEJgBAAD3AQAwmQEBAPwBACGaAQEA_AEAIb0BAQD4AQAhC6IBAQAAAAGjAQEAAAAFpAEBAAAABaUBAQAAAAGmAQEAAAABpwEBAAAAAagBAQAAAAGpAQEA6QEAIbABAQAAAAGxAQEAAAABsgEBAAAAAQO-AQAACwAgvwEAAAsAIMABAAALACAJlgEAAPoBADCXAQAAfAAQmAEAAPoBADCZAQEA3AEAIbQBQADuAQAhwQEBANwBACHCAQEA3AEAIcMBQADuAQAhxAFAAO4BACEJlgEAAPsBADCXAQAAaQAQmAEAAPsBADCZAQEA_AEAIbQBQAD9AQAhwQEBAPwBACHCAQEA_AEAIcMBQAD9AQAhxAFAAP0BACELogEBAAAAAaMBAQAAAASkAQEAAAAEpQEBAAAAAaYBAQAAAAGnAQEAAAABqAEBAAAAAakBAQDrAQAhsAEBAAAAAbEBAQAAAAGyAQEAAAABCKIBQAAAAAGjAUAAAAAEpAFAAAAABKUBQAAAAAGmAUAAAAABpwFAAAAAAagBQAAAAAGpAUAA8AEAIRCWAQAA_gEAMJcBAABjABCYAQAA_gEAMJkBAQDcAQAhoAEBANwBACG0AUAA7gEAIcQBQADuAQAhxQEBANwBACHGAQEA3AEAIccBAQDdAQAhyAEBAN0BACHJAQEA3QEAIcoBQAD_AQAhywFAAP8BACHMAQEA3QEAIc0BAQDdAQAhCwcAAOQBACAgAACBAgAgIQAAgQIAIKIBQAAAAAGjAUAAAAAFpAFAAAAABaUBQAAAAAGmAUAAAAABpwFAAAAAAagBQAAAAAGpAUAAgAIAIQsHAADkAQAgIAAAgQIAICEAAIECACCiAUAAAAABowFAAAAABaQBQAAAAAWlAUAAAAABpgFAAAAAAacBQAAAAAGoAUAAAAABqQFAAIACACEIogFAAAAAAaMBQAAAAAWkAUAAAAAFpQFAAAAAAaYBQAAAAAGnAUAAAAABqAFAAAAAAakBQACBAgAhDJYBAACCAgAwlwEAAE0AEJgBAACCAgAwmQEBANwBACGgAQEA3AEAIbQBQADuAQAhwwFAAO4BACHEAUAA7gEAIc4BAQDcAQAhzwEBAN0BACHQAQEA3QEAIdEBAQDdAQAhD5YBAACDAgAwlwEAADcAEJgBAACDAgAwmQEBANwBACGaAQEA3QEAIbQBQADuAQAhuwEBANwBACHEAUAA7gEAIdIBAQDcAQAh0wEgAIQCACHUAQEA3QEAIdYBAACFAtYBI9cBIACGAgAh2AEBAN0BACHZAUAA_wEAIQUHAADiAQAgIAAAjAIAICEAAIwCACCiASAAAAABqQEgAIsCACEHBwAA5AEAICAAAIoCACAhAACKAgAgogEAAADWAQOjAQAAANYBCaQBAAAA1gEJqQEAAIkC1gEjBQcAAOQBACAgAACIAgAgIQAAiAIAIKIBIAAAAAGpASAAhwIAIQUHAADkAQAgIAAAiAIAICEAAIgCACCiASAAAAABqQEgAIcCACECogEgAAAAAakBIACIAgAhBwcAAOQBACAgAACKAgAgIQAAigIAIKIBAAAA1gEDowEAAADWAQmkAQAAANYBCakBAACJAtYBIwSiAQAAANYBA6MBAAAA1gEJpAEAAADWAQmpAQAAigLWASMFBwAA4gEAICAAAIwCACAhAACMAgAgogEgAAAAAakBIACLAgAhAqIBIAAAAAGpASAAjAIAIRQEAACSAgAgBQAAkwIAIAsAAJUCACAMAACWAgAgDQAAlAIAIJYBAACNAgAwlwEAACQAEJgBAACNAgAwmQEBAPwBACGaAQEA-AEAIbQBQAD9AQAhuwEBAPwBACHEAUAA_QEAIdIBAQD8AQAh0wEgAI4CACHUAQEA-AEAIdYBAACPAtYBI9cBIACQAgAh2AEBAPgBACHZAUAAkQIAIQKiASAAAAABqQEgAIwCACEEogEAAADWAQOjAQAAANYBCaQBAAAA1gEJqQEAAIoC1gEjAqIBIAAAAAGpASAAiAIAIQiiAUAAAAABowFAAAAABaQBQAAAAAWlAUAAAAABpgFAAAAAAacBQAAAAAGoAUAAAAABqQFAAIECACEDvgEAAAMAIL8BAAADACDAAQAAAwAgA74BAAAHACC_AQAABwAgwAEAAAcAIBIDAACZAgAgCAAAoQIAIAsAAJUCACAMAACWAgAglgEAAJ4CADCXAQAACwAQmAEAAJ4CADCZAQEA_AEAIZoBAQD8AQAhmwEBAPgBACGcAQEA-AEAIZ0BCACfAgAhngEAAKACACCfAQgAnQIAIaABAQD8AQAhoQEBAPgBACHaAQAACwAg2wEAAAsAIAO-AQAAEwAgvwEAABMAIMABAAATACADvgEAABcAIL8BAAAXACDAAQAAFwAgCwkAAJkCACAKAACaAgAglgEAAJcCADCXAQAAFwAQmAEAAJcCADCZAQEA_AEAIZ8BAgCYAgAhswEBAPgBACG0AUAA_QEAIbUBAQD8AQAhtgEBAPwBACEIogECAAAAAaMBAgAAAASkAQIAAAAEpQECAAAAAaYBAgAAAAGnAQIAAAABqAECAAAAAakBAgDiAQAhFgQAAJICACAFAACTAgAgCwAAlQIAIAwAAJYCACANAACUAgAglgEAAI0CADCXAQAAJAAQmAEAAI0CADCZAQEA_AEAIZoBAQD4AQAhtAFAAP0BACG7AQEA_AEAIcQBQAD9AQAh0gEBAPwBACHTASAAjgIAIdQBAQD4AQAh1gEAAI8C1gEj1wEgAJACACHYAQEA-AEAIdkBQACRAgAh2gEAACQAINsBAAAkACASAwAAmQIAIAgAAKECACALAACVAgAgDAAAlgIAIJYBAACeAgAwlwEAAAsAEJgBAACeAgAwmQEBAPwBACGaAQEA_AEAIZsBAQD4AQAhnAEBAPgBACGdAQgAnwIAIZ4BAACgAgAgnwEIAJ0CACGgAQEA_AEAIaEBAQD4AQAh2gEAAAsAINsBAAALACANCQAAmQIAIAoAAJoCACCWAQAAmwIAMJcBAAATABCYAQAAmwIAMJkBAQD8AQAhtQEBAPwBACG2AQEA_AEAIbcBQAD9AQAhuAFAAP0BACG5AUAA_QEAIbsBAACcArsBIrwBCACdAgAhBKIBAAAAuwECowEAAAC7AQikAQAAALsBCKkBAAD1AbsBIgiiAQgAAAABowEIAAAABKQBCAAAAASlAQgAAAABpgEIAAAAAacBCAAAAAGoAQgAAAABqQEIAOMBACEQAwAAmQIAIAgAAKECACALAACVAgAgDAAAlgIAIJYBAACeAgAwlwEAAAsAEJgBAACeAgAwmQEBAPwBACGaAQEA_AEAIZsBAQD4AQAhnAEBAPgBACGdAQgAnwIAIZ4BAACgAgAgnwEIAJ0CACGgAQEA_AEAIaEBAQD4AQAhCKIBCAAAAAGjAQgAAAAFpAEIAAAABaUBCAAAAAGmAQgAAAABpwEIAAAAAagBCAAAAAGpAQgA5wEAIQyiAYAAAAABpQGAAAAAAaYBgAAAAAGnAYAAAAABqAGAAAAAAakBgAAAAAGqAQEAAAABqwEBAAAAAawBAQAAAAGtAYAAAAABrgGAAAAAAa8BgAAAAAEJBgAA-QEAIJYBAAD3AQAwlwEAAA0AEJgBAAD3AQAwmQEBAPwBACGaAQEA_AEAIb0BAQD4AQAh2gEAAA0AINsBAAANACARAwAAmQIAIJYBAACiAgAwlwEAAAcAEJgBAACiAgAwmQEBAPwBACGgAQEA_AEAIbQBQAD9AQAhxAFAAP0BACHFAQEA_AEAIcYBAQD8AQAhxwEBAPgBACHIAQEA-AEAIckBAQD4AQAhygFAAJECACHLAUAAkQIAIcwBAQD4AQAhzQEBAPgBACENAwAAmQIAIJYBAACjAgAwlwEAAAMAEJgBAACjAgAwmQEBAPwBACGgAQEA_AEAIbQBQAD9AQAhwwFAAP0BACHEAUAA_QEAIc4BAQD8AQAhzwEBAPgBACHQAQEA-AEAIdEBAQD4AQAhAAAAAAAAAd8BAQAAAAEB3wEBAAAAAQXfAQgAAAAB5QEIAAAAAeYBCAAAAAHnAQgAAAAB6AEIAAAAAQXfAQgAAAAB5QEIAAAAAeYBCAAAAAHnAQgAAAAB6AEIAAAAAQUaAADkAwAgGwAA9gMAINwBAADlAwAg3QEAAPUDACDiAQAAAQAgBxoAAOIDACAbAADzAwAg3AEAAOMDACDdAQAA8gMAIOABAAANACDhAQAADQAg4gEAAH8AIAsaAADCAgAwGwAAxwIAMNwBAADDAgAw3QEAAMQCADDeAQAAxQIAIN8BAADGAgAw4AEAAMYCADDhAQAAxgIAMOIBAADGAgAw4wEAAMgCADDkAQAAyQIAMAsaAACyAgAwGwAAtwIAMNwBAACzAgAw3QEAALQCADDeAQAAtQIAIN8BAAC2AgAw4AEAALYCADDhAQAAtgIAMOIBAAC2AgAw4wEAALgCADDkAQAAuQIAMAYJAADBAgAgmQEBAAAAAZ8BAgAAAAGzAQEAAAABtAFAAAAAAbUBAQAAAAECAAAAGQAgGgAAwAIAIAMAAAAZACAaAADAAgAgGwAAvgIAIAETAADxAwAwCwkAAJkCACAKAACaAgAglgEAAJcCADCXAQAAFwAQmAEAAJcCADCZAQEAAAABnwECAJgCACGzAQEA-AEAIbQBQAD9AQAhtQEBAPwBACG2AQEA_AEAIQIAAAAZACATAAC-AgAgAgAAALoCACATAAC7AgAgCZYBAAC5AgAwlwEAALoCABCYAQAAuQIAMJkBAQD8AQAhnwECAJgCACGzAQEA-AEAIbQBQAD9AQAhtQEBAPwBACG2AQEA_AEAIQmWAQAAuQIAMJcBAAC6AgAQmAEAALkCADCZAQEA_AEAIZ8BAgCYAgAhswEBAPgBACG0AUAA_QEAIbUBAQD8AQAhtgEBAPwBACEFmQEBAKoCACGfAQIAvAIAIbMBAQCrAgAhtAFAAL0CACG1AQEAqgIAIQXfAQIAAAAB5QECAAAAAeYBAgAAAAHnAQIAAAAB6AECAAAAAQHfAUAAAAABBgkAAL8CACCZAQEAqgIAIZ8BAgC8AgAhswEBAKsCACG0AUAAvQIAIbUBAQCqAgAhBRoAAOwDACAbAADvAwAg3AEAAO0DACDdAQAA7gMAIOIBAAABACAGCQAAwQIAIJkBAQAAAAGfAQIAAAABswEBAAAAAbQBQAAAAAG1AQEAAAABAxoAAOwDACDcAQAA7QMAIOIBAAABACAICQAA0AIAIJkBAQAAAAG1AQEAAAABtwFAAAAAAbgBQAAAAAG5AUAAAAABuwEAAAC7AQK8AQgAAAABAgAAABUAIBoAAM8CACADAAAAFQAgGgAAzwIAIBsAAM0CACABEwAA6wMAMA0JAACZAgAgCgAAmgIAIJYBAACbAgAwlwEAABMAEJgBAACbAgAwmQEBAAAAAbUBAQD8AQAhtgEBAPwBACG3AUAA_QEAIbgBQAD9AQAhuQFAAP0BACG7AQAAnAK7ASK8AQgAnQIAIQIAAAAVACATAADNAgAgAgAAAMoCACATAADLAgAgC5YBAADJAgAwlwEAAMoCABCYAQAAyQIAMJkBAQD8AQAhtQEBAPwBACG2AQEA_AEAIbcBQAD9AQAhuAFAAP0BACG5AUAA_QEAIbsBAACcArsBIrwBCACdAgAhC5YBAADJAgAwlwEAAMoCABCYAQAAyQIAMJkBAQD8AQAhtQEBAPwBACG2AQEA_AEAIbcBQAD9AQAhuAFAAP0BACG5AUAA_QEAIbsBAACcArsBIrwBCACdAgAhB5kBAQCqAgAhtQEBAKoCACG3AUAAvQIAIbgBQAC9AgAhuQFAAL0CACG7AQAAzAK7ASK8AQgArQIAIQHfAQAAALsBAggJAADOAgAgmQEBAKoCACG1AQEAqgIAIbcBQAC9AgAhuAFAAL0CACG5AUAAvQIAIbsBAADMArsBIrwBCACtAgAhBRoAAOYDACAbAADpAwAg3AEAAOcDACDdAQAA6AMAIOIBAAABACAICQAA0AIAIJkBAQAAAAG1AQEAAAABtwFAAAAAAbgBQAAAAAG5AUAAAAABuwEAAAC7AQK8AQgAAAABAxoAAOYDACDcAQAA5wMAIOIBAAABACADGgAA5AMAINwBAADlAwAg4gEAAAEAIAMaAADiAwAg3AEAAOMDACDiAQAAfwAgBBoAAMICADDcAQAAwwIAMN4BAADFAgAg4gEAAMYCADAEGgAAsgIAMNwBAACzAgAw3gEAALUCACDiAQAAtgIAMAAAAAAABRoAAN0DACAbAADgAwAg3AEAAN4DACDdAQAA3wMAIOIBAAAQACADGgAA3QMAINwBAADeAwAg4gEAABAAIAAAAAAABRoAANgDACAbAADbAwAg3AEAANkDACDdAQAA2gMAIOIBAAAQACADGgAA2AMAINwBAADZAwAg4gEAABAAIAAAAAsaAADnAgAwGwAA7AIAMNwBAADoAgAw3QEAAOkCADDeAQAA6gIAIN8BAADrAgAw4AEAAOsCADDhAQAA6wIAMOIBAADrAgAw4wEAAO0CADDkAQAA7gIAMAsDAADRAgAgCwAA0wIAIAwAANQCACCZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BgAAAAAGfAQgAAAABoAEBAAAAAQIAAAAQACAaAADyAgAgAwAAABAAIBoAAPICACAbAADxAgAgARMAANcDADAQAwAAmQIAIAgAAKECACALAACVAgAgDAAAlgIAIJYBAACeAgAwlwEAAAsAEJgBAACeAgAwmQEBAAAAAZoBAQD8AQAhmwEBAPgBACGcAQEA-AEAIZ0BCACfAgAhngEAAKACACCfAQgAnQIAIaABAQAAAAGhAQEA-AEAIQIAAAAQACATAADxAgAgAgAAAO8CACATAADwAgAgDJYBAADuAgAwlwEAAO8CABCYAQAA7gIAMJkBAQD8AQAhmgEBAPwBACGbAQEA-AEAIZwBAQD4AQAhnQEIAJ8CACGeAQAAoAIAIJ8BCACdAgAhoAEBAPwBACGhAQEA-AEAIQyWAQAA7gIAMJcBAADvAgAQmAEAAO4CADCZAQEA_AEAIZoBAQD8AQAhmwEBAPgBACGcAQEA-AEAIZ0BCACfAgAhngEAAKACACCfAQgAnQIAIaABAQD8AQAhoQEBAPgBACEImQEBAKoCACGaAQEAqgIAIZsBAQCrAgAhnAEBAKsCACGdAQgArAIAIZ4BgAAAAAGfAQgArQIAIaABAQCqAgAhCwMAAK4CACALAACwAgAgDAAAsQIAIJkBAQCqAgAhmgEBAKoCACGbAQEAqwIAIZwBAQCrAgAhnQEIAKwCACGeAYAAAAABnwEIAK0CACGgAQEAqgIAIQsDAADRAgAgCwAA0wIAIAwAANQCACCZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BgAAAAAGfAQgAAAABoAEBAAAAAQQaAADnAgAw3AEAAOgCADDeAQAA6gIAIOIBAADrAgAwAAAAAAAAAAHfAUAAAAABBRoAANIDACAbAADVAwAg3AEAANMDACDdAQAA1AMAIOIBAAABACADGgAA0gMAINwBAADTAwAg4gEAAAEAIAAAAAUaAADNAwAgGwAA0AMAINwBAADOAwAg3QEAAM8DACDiAQAAAQAgAxoAAM0DACDcAQAAzgMAIOIBAAABACAAAAAB3wEgAAAAAQHfAQAAANYBAwHfASAAAAABCxoAALEDADAbAAC2AwAw3AEAALIDADDdAQAAswMAMN4BAAC0AwAg3wEAALUDADDgAQAAtQMAMOEBAAC1AwAw4gEAALUDADDjAQAAtwMAMOQBAAC4AwAwCxoAAKUDADAbAACqAwAw3AEAAKYDADDdAQAApwMAMN4BAACoAwAg3wEAAKkDADDgAQAAqQMAMOEBAACpAwAw4gEAAKkDADDjAQAAqwMAMOQBAACsAwAwBxoAAKADACAbAACjAwAg3AEAAKEDACDdAQAAogMAIOABAAALACDhAQAACwAg4gEAABAAIAsaAACXAwAwGwAAmwMAMNwBAACYAwAw3QEAAJkDADDeAQAAmgMAIN8BAADGAgAw4AEAAMYCADDhAQAAxgIAMOIBAADGAgAw4wEAAJwDADDkAQAAyQIAMAsaAACOAwAwGwAAkgMAMNwBAACPAwAw3QEAAJADADDeAQAAkQMAIN8BAAC2AgAw4AEAALYCADDhAQAAtgIAMOIBAAC2AgAw4wEAAJMDADDkAQAAuQIAMAYKAADbAgAgmQEBAAAAAZ8BAgAAAAGzAQEAAAABtAFAAAAAAbYBAQAAAAECAAAAGQAgGgAAlgMAIAMAAAAZACAaAACWAwAgGwAAlQMAIAETAADMAwAwAgAAABkAIBMAAJUDACACAAAAugIAIBMAAJQDACAFmQEBAKoCACGfAQIAvAIAIbMBAQCrAgAhtAFAAL0CACG2AQEAqgIAIQYKAADaAgAgmQEBAKoCACGfAQIAvAIAIbMBAQCrAgAhtAFAAL0CACG2AQEAqgIAIQYKAADbAgAgmQEBAAAAAZ8BAgAAAAGzAQEAAAABtAFAAAAAAbYBAQAAAAEICgAA4gIAIJkBAQAAAAG2AQEAAAABtwFAAAAAAbgBQAAAAAG5AUAAAAABuwEAAAC7AQK8AQgAAAABAgAAABUAIBoAAJ8DACADAAAAFQAgGgAAnwMAIBsAAJ4DACABEwAAywMAMAIAAAAVACATAACeAwAgAgAAAMoCACATAACdAwAgB5kBAQCqAgAhtgEBAKoCACG3AUAAvQIAIbgBQAC9AgAhuQFAAL0CACG7AQAAzAK7ASK8AQgArQIAIQgKAADhAgAgmQEBAKoCACG2AQEAqgIAIbcBQAC9AgAhuAFAAL0CACG5AUAAvQIAIbsBAADMArsBIrwBCACtAgAhCAoAAOICACCZAQEAAAABtgEBAAAAAbcBQAAAAAG4AUAAAAABuQFAAAAAAbsBAAAAuwECvAEIAAAAAQsIAADSAgAgCwAA0wIAIAwAANQCACCZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BgAAAAAGfAQgAAAABoQEBAAAAAQIAAAAQACAaAACgAwAgAwAAAAsAIBoAAKADACAbAACkAwAgDQAAAAsAIAgAAK8CACALAACwAgAgDAAAsQIAIBMAAKQDACCZAQEAqgIAIZoBAQCqAgAhmwEBAKsCACGcAQEAqwIAIZ0BCACsAgAhngGAAAAAAZ8BCACtAgAhoQEBAKsCACELCAAArwIAIAsAALACACAMAACxAgAgmQEBAKoCACGaAQEAqgIAIZsBAQCrAgAhnAEBAKsCACGdAQgArAIAIZ4BgAAAAAGfAQgArQIAIaEBAQCrAgAhDJkBAQAAAAG0AUAAAAABxAFAAAAAAcUBAQAAAAHGAQEAAAABxwEBAAAAAcgBAQAAAAHJAQEAAAABygFAAAAAAcsBQAAAAAHMAQEAAAABzQEBAAAAAQIAAAAJACAaAACwAwAgAwAAAAkAIBoAALADACAbAACvAwAgARMAAMoDADARAwAAmQIAIJYBAACiAgAwlwEAAAcAEJgBAACiAgAwmQEBAAAAAaABAQD8AQAhtAFAAP0BACHEAUAA_QEAIcUBAQD8AQAhxgEBAPwBACHHAQEA-AEAIcgBAQD4AQAhyQEBAPgBACHKAUAAkQIAIcsBQACRAgAhzAEBAPgBACHNAQEA-AEAIQIAAAAJACATAACvAwAgAgAAAK0DACATAACuAwAgEJYBAACsAwAwlwEAAK0DABCYAQAArAMAMJkBAQD8AQAhoAEBAPwBACG0AUAA_QEAIcQBQAD9AQAhxQEBAPwBACHGAQEA_AEAIccBAQD4AQAhyAEBAPgBACHJAQEA-AEAIcoBQACRAgAhywFAAJECACHMAQEA-AEAIc0BAQD4AQAhEJYBAACsAwAwlwEAAK0DABCYAQAArAMAMJkBAQD8AQAhoAEBAPwBACG0AUAA_QEAIcQBQAD9AQAhxQEBAPwBACHGAQEA_AEAIccBAQD4AQAhyAEBAPgBACHJAQEA-AEAIcoBQACRAgAhywFAAJECACHMAQEA-AEAIc0BAQD4AQAhDJkBAQCqAgAhtAFAAL0CACHEAUAAvQIAIcUBAQCqAgAhxgEBAKoCACHHAQEAqwIAIcgBAQCrAgAhyQEBAKsCACHKAUAA-wIAIcsBQAD7AgAhzAEBAKsCACHNAQEAqwIAIQyZAQEAqgIAIbQBQAC9AgAhxAFAAL0CACHFAQEAqgIAIcYBAQCqAgAhxwEBAKsCACHIAQEAqwIAIckBAQCrAgAhygFAAPsCACHLAUAA-wIAIcwBAQCrAgAhzQEBAKsCACEMmQEBAAAAAbQBQAAAAAHEAUAAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAHKAUAAAAABywFAAAAAAcwBAQAAAAHNAQEAAAABCJkBAQAAAAG0AUAAAAABwwFAAAAAAcQBQAAAAAHOAQEAAAABzwEBAAAAAdABAQAAAAHRAQEAAAABAgAAAAUAIBoAALwDACADAAAABQAgGgAAvAMAIBsAALsDACABEwAAyQMAMA0DAACZAgAglgEAAKMCADCXAQAAAwAQmAEAAKMCADCZAQEAAAABoAEBAPwBACG0AUAA_QEAIcMBQAD9AQAhxAFAAP0BACHOAQEAAAABzwEBAPgBACHQAQEA-AEAIdEBAQD4AQAhAgAAAAUAIBMAALsDACACAAAAuQMAIBMAALoDACAMlgEAALgDADCXAQAAuQMAEJgBAAC4AwAwmQEBAPwBACGgAQEA_AEAIbQBQAD9AQAhwwFAAP0BACHEAUAA_QEAIc4BAQD8AQAhzwEBAPgBACHQAQEA-AEAIdEBAQD4AQAhDJYBAAC4AwAwlwEAALkDABCYAQAAuAMAMJkBAQD8AQAhoAEBAPwBACG0AUAA_QEAIcMBQAD9AQAhxAFAAP0BACHOAQEA_AEAIc8BAQD4AQAh0AEBAPgBACHRAQEA-AEAIQiZAQEAqgIAIbQBQAC9AgAhwwFAAL0CACHEAUAAvQIAIc4BAQCqAgAhzwEBAKsCACHQAQEAqwIAIdEBAQCrAgAhCJkBAQCqAgAhtAFAAL0CACHDAUAAvQIAIcQBQAC9AgAhzgEBAKoCACHPAQEAqwIAIdABAQCrAgAh0QEBAKsCACEImQEBAAAAAbQBQAAAAAHDAUAAAAABxAFAAAAAAc4BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAEEGgAAsQMAMNwBAACyAwAw3gEAALQDACDiAQAAtQMAMAQaAAClAwAw3AEAAKYDADDeAQAAqAMAIOIBAACpAwAwAxoAAKADACDcAQAAoQMAIOIBAAAQACAEGgAAlwMAMNwBAACYAwAw3gEAAJoDACDiAQAAxgIAMAQaAACOAwAw3AEAAI8DADDeAQAAkQMAIOIBAAC2AgAwAAAJAwAAxwMAIAgAAMgDACALAADFAwAgDAAAxgMAIJsBAACkAgAgnAEAAKQCACCdAQAApAIAIJ4BAACkAgAgoQEAAKQCACAAAAsEAADCAwAgBQAAwwMAIAsAAMUDACAMAADGAwAgDQAAxAMAIJoBAACkAgAg1AEAAKQCACDWAQAApAIAINcBAACkAgAg2AEAAKQCACDZAQAApAIAIAIGAAD0AgAgvQEAAKQCACAImQEBAAAAAbQBQAAAAAHDAUAAAAABxAFAAAAAAc4BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAEMmQEBAAAAAbQBQAAAAAHEAUAAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAHKAUAAAAABywFAAAAAAcwBAQAAAAHNAQEAAAABB5kBAQAAAAG2AQEAAAABtwFAAAAAAbgBQAAAAAG5AUAAAAABuwEAAAC7AQK8AQgAAAABBZkBAQAAAAGfAQIAAAABswEBAAAAAbQBQAAAAAG2AQEAAAABEAUAAL4DACALAADAAwAgDAAAwQMAIA0AAL8DACCZAQEAAAABmgEBAAAAAbQBQAAAAAG7AQEAAAABxAFAAAAAAdIBAQAAAAHTASAAAAAB1AEBAAAAAdYBAAAA1gED1wEgAAAAAdgBAQAAAAHZAUAAAAABAgAAAAEAIBoAAM0DACADAAAAJAAgGgAAzQMAIBsAANEDACASAAAAJAAgBQAAigMAIAsAAIwDACAMAACNAwAgDQAAiwMAIBMAANEDACCZAQEAqgIAIZoBAQCrAgAhtAFAAL0CACG7AQEAqgIAIcQBQAC9AgAh0gEBAKoCACHTASAAhgMAIdQBAQCrAgAh1gEAAIcD1gEj1wEgAIgDACHYAQEAqwIAIdkBQAD7AgAhEAUAAIoDACALAACMAwAgDAAAjQMAIA0AAIsDACCZAQEAqgIAIZoBAQCrAgAhtAFAAL0CACG7AQEAqgIAIcQBQAC9AgAh0gEBAKoCACHTASAAhgMAIdQBAQCrAgAh1gEAAIcD1gEj1wEgAIgDACHYAQEAqwIAIdkBQAD7AgAhEAQAAL0DACALAADAAwAgDAAAwQMAIA0AAL8DACCZAQEAAAABmgEBAAAAAbQBQAAAAAG7AQEAAAABxAFAAAAAAdIBAQAAAAHTASAAAAAB1AEBAAAAAdYBAAAA1gED1wEgAAAAAdgBAQAAAAHZAUAAAAABAgAAAAEAIBoAANIDACADAAAAJAAgGgAA0gMAIBsAANYDACASAAAAJAAgBAAAiQMAIAsAAIwDACAMAACNAwAgDQAAiwMAIBMAANYDACCZAQEAqgIAIZoBAQCrAgAhtAFAAL0CACG7AQEAqgIAIcQBQAC9AgAh0gEBAKoCACHTASAAhgMAIdQBAQCrAgAh1gEAAIcD1gEj1wEgAIgDACHYAQEAqwIAIdkBQAD7AgAhEAQAAIkDACALAACMAwAgDAAAjQMAIA0AAIsDACCZAQEAqgIAIZoBAQCrAgAhtAFAAL0CACG7AQEAqgIAIcQBQAC9AgAh0gEBAKoCACHTASAAhgMAIdQBAQCrAgAh1gEAAIcD1gEj1wEgAIgDACHYAQEAqwIAIdkBQAD7AgAhCJkBAQAAAAGaAQEAAAABmwEBAAAAAZwBAQAAAAGdAQgAAAABngGAAAAAAZ8BCAAAAAGgAQEAAAABDAMAANECACAIAADSAgAgDAAA1AIAIJkBAQAAAAGaAQEAAAABmwEBAAAAAZwBAQAAAAGdAQgAAAABngGAAAAAAZ8BCAAAAAGgAQEAAAABoQEBAAAAAQIAAAAQACAaAADYAwAgAwAAAAsAIBoAANgDACAbAADcAwAgDgAAAAsAIAMAAK4CACAIAACvAgAgDAAAsQIAIBMAANwDACCZAQEAqgIAIZoBAQCqAgAhmwEBAKsCACGcAQEAqwIAIZ0BCACsAgAhngGAAAAAAZ8BCACtAgAhoAEBAKoCACGhAQEAqwIAIQwDAACuAgAgCAAArwIAIAwAALECACCZAQEAqgIAIZoBAQCqAgAhmwEBAKsCACGcAQEAqwIAIZ0BCACsAgAhngGAAAAAAZ8BCACtAgAhoAEBAKoCACGhAQEAqwIAIQwDAADRAgAgCAAA0gIAIAsAANMCACCZAQEAAAABmgEBAAAAAZsBAQAAAAGcAQEAAAABnQEIAAAAAZ4BgAAAAAGfAQgAAAABoAEBAAAAAaEBAQAAAAECAAAAEAAgGgAA3QMAIAMAAAALACAaAADdAwAgGwAA4QMAIA4AAAALACADAACuAgAgCAAArwIAIAsAALACACATAADhAwAgmQEBAKoCACGaAQEAqgIAIZsBAQCrAgAhnAEBAKsCACGdAQgArAIAIZ4BgAAAAAGfAQgArQIAIaABAQCqAgAhoQEBAKsCACEMAwAArgIAIAgAAK8CACALAACwAgAgmQEBAKoCACGaAQEAqgIAIZsBAQCrAgAhnAEBAKsCACGdAQgArAIAIZ4BgAAAAAGfAQgArQIAIaABAQCqAgAhoQEBAKsCACEDmQEBAAAAAZoBAQAAAAG9AQEAAAABAgAAAH8AIBoAAOIDACAQBAAAvQMAIAUAAL4DACALAADAAwAgDAAAwQMAIJkBAQAAAAGaAQEAAAABtAFAAAAAAbsBAQAAAAHEAUAAAAAB0gEBAAAAAdMBIAAAAAHUAQEAAAAB1gEAAADWAQPXASAAAAAB2AEBAAAAAdkBQAAAAAECAAAAAQAgGgAA5AMAIBAEAAC9AwAgBQAAvgMAIAwAAMEDACANAAC_AwAgmQEBAAAAAZoBAQAAAAG0AUAAAAABuwEBAAAAAcQBQAAAAAHSAQEAAAAB0wEgAAAAAdQBAQAAAAHWAQAAANYBA9cBIAAAAAHYAQEAAAAB2QFAAAAAAQIAAAABACAaAADmAwAgAwAAACQAIBoAAOYDACAbAADqAwAgEgAAACQAIAQAAIkDACAFAACKAwAgDAAAjQMAIA0AAIsDACATAADqAwAgmQEBAKoCACGaAQEAqwIAIbQBQAC9AgAhuwEBAKoCACHEAUAAvQIAIdIBAQCqAgAh0wEgAIYDACHUAQEAqwIAIdYBAACHA9YBI9cBIACIAwAh2AEBAKsCACHZAUAA-wIAIRAEAACJAwAgBQAAigMAIAwAAI0DACANAACLAwAgmQEBAKoCACGaAQEAqwIAIbQBQAC9AgAhuwEBAKoCACHEAUAAvQIAIdIBAQCqAgAh0wEgAIYDACHUAQEAqwIAIdYBAACHA9YBI9cBIACIAwAh2AEBAKsCACHZAUAA-wIAIQeZAQEAAAABtQEBAAAAAbcBQAAAAAG4AUAAAAABuQFAAAAAAbsBAAAAuwECvAEIAAAAARAEAAC9AwAgBQAAvgMAIAsAAMADACANAAC_AwAgmQEBAAAAAZoBAQAAAAG0AUAAAAABuwEBAAAAAcQBQAAAAAHSAQEAAAAB0wEgAAAAAdQBAQAAAAHWAQAAANYBA9cBIAAAAAHYAQEAAAAB2QFAAAAAAQIAAAABACAaAADsAwAgAwAAACQAIBoAAOwDACAbAADwAwAgEgAAACQAIAQAAIkDACAFAACKAwAgCwAAjAMAIA0AAIsDACATAADwAwAgmQEBAKoCACGaAQEAqwIAIbQBQAC9AgAhuwEBAKoCACHEAUAAvQIAIdIBAQCqAgAh0wEgAIYDACHUAQEAqwIAIdYBAACHA9YBI9cBIACIAwAh2AEBAKsCACHZAUAA-wIAIRAEAACJAwAgBQAAigMAIAsAAIwDACANAACLAwAgmQEBAKoCACGaAQEAqwIAIbQBQAC9AgAhuwEBAKoCACHEAUAAvQIAIdIBAQCqAgAh0wEgAIYDACHUAQEAqwIAIdYBAACHA9YBI9cBIACIAwAh2AEBAKsCACHZAUAA-wIAIQWZAQEAAAABnwECAAAAAbMBAQAAAAG0AUAAAAABtQEBAAAAAQMAAAANACAaAADiAwAgGwAA9AMAIAUAAAANACATAAD0AwAgmQEBAKoCACGaAQEAqgIAIb0BAQCrAgAhA5kBAQCqAgAhmgEBAKoCACG9AQEAqwIAIQMAAAAkACAaAADkAwAgGwAA9wMAIBIAAAAkACAEAACJAwAgBQAAigMAIAsAAIwDACAMAACNAwAgEwAA9wMAIJkBAQCqAgAhmgEBAKsCACG0AUAAvQIAIbsBAQCqAgAhxAFAAL0CACHSAQEAqgIAIdMBIACGAwAh1AEBAKsCACHWAQAAhwPWASPXASAAiAMAIdgBAQCrAgAh2QFAAPsCACEQBAAAiQMAIAUAAIoDACALAACMAwAgDAAAjQMAIJkBAQCqAgAhmgEBAKsCACG0AUAAvQIAIbsBAQCqAgAhxAFAAL0CACHSAQEAqgIAIdMBIACGAwAh1AEBAKsCACHWAQAAhwPWASPXASAAiAMAIdgBAQCrAgAh2QFAAPsCACEGBAYCBQoDBwAKCx0HDB4IDQwEAQMAAQEDAAEFAwABBwAJCA4FCxYHDBoIAgYRBAcABgEGEgACCQABCgAEAgkAAQoABAILGwAMHAAEBB8ABSAACyEADCIAAAAAAwcADyAAECEAEQAAAAMHAA8gABAhABEBAwABAQMAAQMHABYgABchABgAAAADBwAWIAAXIQAYAQMAAQEDAAEDBwAdIAAeIQAfAAAAAwcAHSAAHiEAHwAAAAMHACUgACYhACcAAAADBwAlIAAmIQAnAAADBwAsIAAtIQAuAAAAAwcALCAALSEALgIJAAEKAAQCCQABCgAEBQcAMyAANiEAN3IANHMANQAAAAAABQcAMyAANiEAN3IANHMANQIJAAEKAAQCCQABCgAEBQcAPCAAPyEAQHIAPXMAPgAAAAAABQcAPCAAPyEAQHIAPXMAPgIDAAEIzQEFAgMAAQjTAQUFBwBFIABIIQBJcgBGcwBHAAAAAAAFBwBFIABIIQBJcgBGcwBHDgIBDyMBECYBEScBEigBFCoBFSwLFi0MFy8BGDELGTINHDMBHTQBHjULIjgOIzkSJDoCJTsCJjwCJz0CKD4CKUACKkILK0MTLEUCLUcLLkgUL0kCMEoCMUsLMk4VM08ZNFADNVEDNlIDN1MDOFQDOVYDOlgLO1kaPFsDPV0LPl4bP18DQGADQWELQmQcQ2UgRGchRWghRmshR2whSG0hSW8hSnELS3IiTHQhTXYLTncjT3ghUHkhUXoLUn0kU34oVIABBVWBAQVWgwEFV4QBBViFAQVZhwEFWokBC1uKASlcjAEFXY4BC16PASpfkAEFYJEBBWGSAQtilQErY5YBL2SXAQdlmAEHZpkBB2eaAQdomwEHaZ0BB2qfAQtroAEwbKIBB22kAQtupQExb6YBB3CnAQdxqAELdKsBMnWsATh2rQEId64BCHivAQh5sAEIerEBCHuzAQh8tQELfbYBOX64AQh_ugELgAG7ATqBAbwBCIIBvQEIgwG-AQuEAcEBO4UBwgFBhgHDAQSHAcQBBIgBxQEEiQHGAQSKAccBBIsByQEEjAHLAQuNAcwBQo4BzwEEjwHRAQuQAdIBQ5EB1AEEkgHVAQSTAdYBC5QB2QFElQHaAUo"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer: Buffer2 } = await import("buffer");
  const wasmArray = Buffer2.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// src/generated/prisma/internal/prismaNamespace.ts
var prismaNamespace_exports = {};
__export(prismaNamespace_exports, {
  AccountScalarFieldEnum: () => AccountScalarFieldEnum,
  AnyNull: () => AnyNull2,
  BookingScalarFieldEnum: () => BookingScalarFieldEnum,
  CategoryScalarFieldEnum: () => CategoryScalarFieldEnum,
  DbNull: () => DbNull2,
  Decimal: () => Decimal2,
  JsonNull: () => JsonNull2,
  JsonNullValueFilter: () => JsonNullValueFilter,
  ModelName: () => ModelName,
  NullTypes: () => NullTypes2,
  NullableJsonNullValueInput: () => NullableJsonNullValueInput,
  NullsOrder: () => NullsOrder,
  PrismaClientInitializationError: () => PrismaClientInitializationError2,
  PrismaClientKnownRequestError: () => PrismaClientKnownRequestError2,
  PrismaClientRustPanicError: () => PrismaClientRustPanicError2,
  PrismaClientUnknownRequestError: () => PrismaClientUnknownRequestError2,
  PrismaClientValidationError: () => PrismaClientValidationError2,
  QueryMode: () => QueryMode,
  ReviewScalarFieldEnum: () => ReviewScalarFieldEnum,
  SessionScalarFieldEnum: () => SessionScalarFieldEnum,
  SortOrder: () => SortOrder,
  Sql: () => Sql2,
  TransactionIsolationLevel: () => TransactionIsolationLevel,
  TutorProfileScalarFieldEnum: () => TutorProfileScalarFieldEnum,
  UserScalarFieldEnum: () => UserScalarFieldEnum,
  VerificationScalarFieldEnum: () => VerificationScalarFieldEnum,
  defineExtension: () => defineExtension,
  empty: () => empty2,
  getExtensionContext: () => getExtensionContext,
  join: () => join2,
  prismaVersion: () => prismaVersion,
  raw: () => raw2,
  sql: () => sql
});
import * as runtime2 from "@prisma/client/runtime/client";
var PrismaClientKnownRequestError2 = runtime2.PrismaClientKnownRequestError;
var PrismaClientUnknownRequestError2 = runtime2.PrismaClientUnknownRequestError;
var PrismaClientRustPanicError2 = runtime2.PrismaClientRustPanicError;
var PrismaClientInitializationError2 = runtime2.PrismaClientInitializationError;
var PrismaClientValidationError2 = runtime2.PrismaClientValidationError;
var sql = runtime2.sqltag;
var empty2 = runtime2.empty;
var join2 = runtime2.join;
var raw2 = runtime2.raw;
var Sql2 = runtime2.Sql;
var Decimal2 = runtime2.Decimal;
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var prismaVersion = {
  client: "7.4.0",
  engine: "ab56fe763f921d033a6c195e7ddeb3e255bdbb57"
};
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var DbNull2 = runtime2.DbNull;
var JsonNull2 = runtime2.JsonNull;
var AnyNull2 = runtime2.AnyNull;
var ModelName = {
  User: "User",
  Session: "Session",
  Account: "Account",
  Verification: "Verification",
  Category: "Category",
  Booking: "Booking",
  Review: "Review",
  TutorProfile: "TutorProfile"
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  emailVerified: "emailVerified",
  image: "image",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  status: "status",
  role: "role",
  banned: "banned",
  banReason: "banReason",
  banExpires: "banExpires"
};
var SessionScalarFieldEnum = {
  id: "id",
  expiresAt: "expiresAt",
  token: "token",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  ipAddress: "ipAddress",
  userAgent: "userAgent",
  userId: "userId",
  impersonatedBy: "impersonatedBy"
};
var AccountScalarFieldEnum = {
  id: "id",
  accountId: "accountId",
  providerId: "providerId",
  userId: "userId",
  accessToken: "accessToken",
  refreshToken: "refreshToken",
  idToken: "idToken",
  accessTokenExpiresAt: "accessTokenExpiresAt",
  refreshTokenExpiresAt: "refreshTokenExpiresAt",
  scope: "scope",
  password: "password",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var VerificationScalarFieldEnum = {
  id: "id",
  identifier: "identifier",
  value: "value",
  expiresAt: "expiresAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var CategoryScalarFieldEnum = {
  id: "id",
  name: "name",
  description: "description"
};
var BookingScalarFieldEnum = {
  id: "id",
  sessionDate: "sessionDate",
  startTime: "startTime",
  endTime: "endTime",
  status: "status",
  price: "price",
  studentId: "studentId",
  tutorId: "tutorId"
};
var ReviewScalarFieldEnum = {
  id: "id",
  rating: "rating",
  comment: "comment",
  createdAt: "createdAt",
  studentId: "studentId",
  tutorId: "tutorId"
};
var TutorProfileScalarFieldEnum = {
  id: "id",
  name: "name",
  bio: "bio",
  experience: "experience",
  hourlyRate: "hourlyRate",
  availability: "availability",
  rating: "rating",
  userId: "userId",
  categoryId: "categoryId"
};
var SortOrder = {
  asc: "asc",
  desc: "desc"
};
var NullableJsonNullValueInput = {
  DbNull: DbNull2,
  JsonNull: JsonNull2
};
var QueryMode = {
  default: "default",
  insensitive: "insensitive"
};
var NullsOrder = {
  first: "first",
  last: "last"
};
var JsonNullValueFilter = {
  DbNull: DbNull2,
  JsonNull: JsonNull2,
  AnyNull: AnyNull2
};
var defineExtension = runtime2.Extensions.defineExtension;

// src/generated/prisma/enums.ts
var BookingStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
};

// src/generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var rawConnectionString = process.env.DATABASE_URL || "";
if (!rawConnectionString) {
  throw new Error("DATABASE_URL is not set");
}
var ensureSslMode = (url) => {
  if (url.includes("sslmode=")) {
    return url;
  }
  const separator = url.includes("?") ? "&" : "?";
  return `${url}${separator}sslmode=verify-full`;
};
var connectionString = ensureSslMode(rawConnectionString);
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
var auth = betterAuth({
  baseURL: process.env.BETTER_AUTH_URL || "http://localhost:5000",
  trustedOrigins: [
    "https://assingment-4-frontend.vercel.app",
    process.env.APP_URL || "http://localhost:4000",
    process.env.CLIENT_URL || "http://localhost:3000"
  ],
  // plugins: [admin({ defaultRole: "Student" })],
  database: prismaAdapter(prisma, {
    provider: "postgresql"
  }),
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "Student",
        required: false
      },
      status: {
        type: "string",
        defaultValue: "active",
        required: false
      }
    }
  },
  emailAndPassword: {
    enabled: true
  },
  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    }
  },
  session: {
    cookieCache: {
      enabled: true,
      maxAge: 5 * 60
      // 5 minutes
    }
  },
  advanced: {
    cookiePrefix: "better-auth",
    useSecureCookies: process.env.NODE_ENV === "production",
    crossSubDomainCookies: {
      enabled: false
    },
    disableCSRFCheck: true
    // Allow requests without Origin header (Postman, mobile apps, etc.)
  }
});

// src/modules/category/category.route.ts
import { Router } from "express";

// src/modules/category/category.service.ts
var createCategory = async (payload) => {
  console.log(payload);
  const result = await prisma.category.create({
    data: payload
  });
  return result;
};
var getCategories = async () => {
  const result = await prisma.category.findMany({
    include: {
      tutors: true
    }
  });
  return result;
};
var categoryService = {
  createCategory,
  getCategories
};

// src/modules/category/category.controller.ts
var createCategory2 = async (req, res) => {
  try {
    const payload = req.body;
    const category = await categoryService.createCategory(payload);
    res.status(201).json(category);
  } catch (error) {
    if (error instanceof prismaNamespace_exports.PrismaClientKnownRequestError && error.code === "P2002") {
      return res.status(400).json({
        message: "Category name must be unique. This name already exists."
      });
    }
    console.error("Error creating category:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
var getCategories2 = async (req, res) => {
  try {
    const categories = await categoryService.getCategories();
    res.status(200).json(categories);
  } catch (error) {
    console.error("Error fetching categories:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
var categoryController = {
  createCategory: createCategory2,
  getCategories: getCategories2
};

// src/modules/category/category.route.ts
var router = Router();
router.post("/", categoryController.createCategory);
router.get("/", categoryController.getCategories);
var categoryRoute = router;

// src/modules/tutorProfile/tutorProfile.route.ts
import { Router as Router2 } from "express";

// src/helpers/paginationSortingHelper.ts
var paginationSortinghelper = (options) => {
  const page = Number(options.page) || 1;
  const limit = Number(options.limit) || 5;
  const skip = (page - 1) * limit;
  const sortBy = options.sortBy || "createdAt";
  const sortOrder = options.sortOrder || "desc";
  return {
    page,
    limit,
    skip,
    sortBy,
    sortOrder
  };
};
var paginationSortingHelper_default = paginationSortinghelper;

// src/modules/tutorProfile/tutorProfile.servic.ts
var createTutorProfile = async (payload, userId) => {
  console.log(payload);
  const { name, bio, experience, hourlyRate, availability, categoryId } = payload;
  const result = await prisma.tutorProfile.create({
    data: {
      name,
      bio,
      experience,
      hourlyRate: hourlyRate ? Number(hourlyRate) : void 0,
      availability: availability ?? void 0,
      categoryId: categoryId ?? void 0,
      userId
    },
    include: {
      user: true,
      category: true
    }
  });
  return result;
};
var getTutorProfile = async (payload, page, limit, skip, sortBy, sortOrder) => {
  const whereClause = [];
  if (payload.search) {
    whereClause.push({
      OR: [
        {
          name: {
            contains: payload.search,
            mode: "insensitive"
          }
        },
        {
          bio: {
            contains: payload.search,
            mode: "insensitive"
          }
        },
        {
          experience: {
            contains: payload.search,
            mode: "insensitive"
          }
        },
        {
          category: {
            name: {
              contains: payload.search,
              mode: "insensitive"
            }
          }
        },
        {
          category: {
            description: {
              contains: payload.search,
              mode: "insensitive"
            }
          }
        }
      ]
    });
  }
  const validSortFields = [
    "id",
    "name",
    "bio",
    "experience",
    "hourlyRate",
    "availability",
    "rating",
    "userId",
    "categoryId"
  ];
  const safeSortBy = validSortFields.includes(sortBy) ? sortBy : "id";
  const result = await prisma.tutorProfile.findMany({
    take: limit || 10,
    skip: skip || 0,
    where: {
      AND: whereClause
    },
    orderBy: {
      [safeSortBy]: sortOrder
    },
    include: {
      user: true,
      category: true,
      bookings: true,
      reviews: true
    }
  });
  const count = await prisma.tutorProfile.count({
    where: {
      AND: whereClause
    }
  });
  return {
    data: result,
    pagination: {
      total: count,
      page,
      limit,
      totalPages: Math.ceil(count / limit)
    }
  };
};
var getTutorProfileByuserId = async (TutorId) => {
  const result = await prisma.tutorProfile.findUnique({
    where: {
      id: TutorId
    },
    include: {
      user: true,
      category: true,
      bookings: true,
      reviews: true
    }
  });
  return result;
};
var updateTutorProfile = async (TutorId, payload) => {
  const result = await prisma.tutorProfile.update({
    where: {
      id: TutorId
    },
    data: payload
  });
  return result;
};
var tutorProfileService = {
  createTutorProfile,
  getTutorProfile,
  getTutorProfileByuserId,
  updateTutorProfile
};

// src/modules/tutorProfile/tutorProfile.controller.ts
var createTutorProfile2 = async (req, res) => {
  try {
    const payload = req.body;
    const user = req.user;
    if (!user) {
      return res.status(401).json({ message: "Unauthorized" });
    }
    const tutorProfile = await tutorProfileService.createTutorProfile(
      payload,
      user.userId
    );
    res.status(201).json(tutorProfile);
  } catch (error) {
    console.error("Error creating tutor profile:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
var getTutorProfile2 = async (req, res) => {
  try {
    const { search } = req.query;
    const { page, limit, skip, sortBy, sortOrder } = paginationSortingHelper_default(
      req.query
    );
    const tutorProfile = await tutorProfileService.getTutorProfile(
      {
        search
      },
      page,
      limit,
      skip,
      sortBy,
      sortOrder
    );
    res.status(200).json(tutorProfile);
  } catch (error) {
    console.error("Error fetching tutor profiles:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
var getTutorProfileByuserId2 = async (req, res) => {
  try {
    const { TutorId } = req.params;
    if (!TutorId) {
      throw new Error("TutorId is required");
    }
    const result = await tutorProfileService.getTutorProfileByuserId(
      TutorId
    );
    res.status(200).json({ result });
  } catch (error) {
    console.error("Error fetching tutor profile by user id:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
var updateTutorProfile2 = async (req, res) => {
  try {
    const { TutorId } = req.params;
    const payload = req.body;
    const { userId } = req.user || {};
    if (!TutorId) {
      return res.status(400).json({ message: "TutorId is required" });
    }
    const result = await tutorProfileService.updateTutorProfile(
      TutorId,
      payload
    );
    res.status(200).json({ result });
  } catch (error) {
    console.error("Error updating tutor profile:", error);
    res.status(500).json({ message: "Internal server error" });
  }
};
var tutorProfileController = {
  createTutorProfile: createTutorProfile2,
  getTutorProfile: getTutorProfile2,
  getTutorProfileByuserId: getTutorProfileByuserId2,
  updateTutorProfile: updateTutorProfile2
};

// src/modules/tutorProfile/tutorProfile.route.ts
var router2 = Router2();
var auth2 = (...roles) => {
  return async (req, res, next) => {
    console.log("auth middleware", roles);
    const session = await auth.api.getSession({
      headers: req.headers
    });
    if (!session || !session.user) {
      return res.status(401).json({ message: "Unauthorized" });
    }
    req.user = {
      userId: session.user.id,
      email: session.user.email,
      name: session.user.name,
      role: session.user.role || "Student"
    };
    if (roles.length > 0 && !roles.includes(req.user.role)) {
      return res.status(403).json({ message: "Forbidden" });
    }
    next();
  };
};
router2.post(
  "/",
  auth2("Tutor" /* Tutor */),
  tutorProfileController.createTutorProfile
);
router2.put(
  "/tutor/:TutorId",
  auth2("Tutor" /* Tutor */),
  tutorProfileController.updateTutorProfile
);
router2.get("/:TutorId", tutorProfileController.getTutorProfileByuserId);
router2.get("/", tutorProfileController.getTutorProfile);
var tutorProfileRoute = router2;

// src/modules/booking/booking.route.ts
import { Router as Router3 } from "express";

// src/modules/booking/booking.service.ts
var createBooking = async (payload, studentId) => {
  const result = await prisma.booking.create({
    data: {
      ...payload,
      studentId
    },
    include: {
      tutor: true,
      student: true
    }
  });
  return result;
};
var getStudentBookings = async (studentId) => {
  const result = await prisma.booking.findMany({
    where: {
      studentId
    },
    include: {
      tutor: true,
      student: true
    }
  });
  return result;
};
var getTutorBookings = async (userId) => {
  const tutorProfile = await prisma.tutorProfile.findUnique({
    where: { userId }
  });
  if (!tutorProfile) {
    return [];
  }
  const result = await prisma.booking.findMany({
    where: {
      tutorId: tutorProfile.id
    },
    include: {
      tutor: true,
      student: true
    }
  });
  return result;
};
var updateStudentBookingStatus = async (bookingId) => {
  const result = await prisma.booking.update({
    where: {
      id: bookingId
    },
    data: {
      status: "CANCELLED"
    }
  });
  return result;
};
var updateTutorBookingStatus = async (bookingId, status) => {
  const result = await prisma.booking.update({
    where: {
      id: bookingId
    },
    data: {
      status: "COMPLETED"
    }
  });
  return result;
};
var showAllBookings = async () => {
  const result = await prisma.booking.findMany({
    include: {
      tutor: true,
      student: true
    }
  });
  return result;
};
var bookingService = {
  createBooking,
  getStudentBookings,
  getTutorBookings,
  updateStudentBookingStatus,
  updateTutorBookingStatus,
  showAllBookings
};

// src/modules/booking/booking.controller.ts
var createBooking2 = async (req, res) => {
  try {
    const { userId } = req.user;
    const payload = req.body;
    const result = await bookingService.createBooking(
      payload,
      userId
    );
    res.status(201).json(result);
  } catch (error) {
    res.status(500).json({ message: "Failed to create booking", error });
  }
};
var getStudentBookings2 = async (req, res) => {
  try {
    const { userId, role } = req.user;
    if (role !== "Student") {
      return res.status(403).json({ message: "You are not authorized to view student bookings" });
    }
    const result = await bookingService.getStudentBookings(userId);
    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({ message: "Failed to get bookings", error });
  }
};
var getTutorBookings2 = async (req, res) => {
  try {
    const { userId, role } = req.user;
    if (role !== "Tutor") {
      return res.status(403).json({ message: "You are not authorized to view tutor bookings" });
    }
    const result = await bookingService.getTutorBookings(userId);
    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({ message: "Failed to get bookings", error });
  }
};
var updateBookingStatus = async (req, res) => {
  try {
    const { bookingId } = req.params;
    const { role } = req.user;
    if (role === "Student") {
      const result = await bookingService.updateStudentBookingStatus(
        bookingId
      );
      res.status(200).json(result);
    } else if (role === "Tutor") {
      const result = await bookingService.updateTutorBookingStatus(
        bookingId,
        "COMPLETED"
      );
      res.status(200).json(result);
    }
  } catch (error) {
    res.status(500).json({ message: "Failed to update booking status", error });
  }
};
var showAllBookings2 = async (req, res) => {
  try {
    const result = await bookingService.showAllBookings();
    res.status(200).json(result);
  } catch (error) {
    res.status(500).json({ message: "Failed to get bookings", error });
  }
};
var bookingController = {
  createBooking: createBooking2,
  getStudentBookings: getStudentBookings2,
  getTutorBookings: getTutorBookings2,
  updateBookingStatus,
  showAllBookings: showAllBookings2
};

// src/modules/booking/booking.route.ts
var router3 = Router3();
router3.post("/", auth2("Student" /* Student */), bookingController.createBooking);
router3.get(
  "/student",
  auth2("Student" /* Student */),
  bookingController.getStudentBookings
);
router3.get("/tutor", auth2("Tutor" /* Tutor */), bookingController.getTutorBookings);
router3.put(
  "/:bookingId/status",
  auth2("Student" /* Student */, "Tutor" /* Tutor */),
  bookingController.updateBookingStatus
);
router3.get("/all", bookingController.showAllBookings);
var bookingRoute = router3;

// src/modules/reviwe/review.route.ts
import { Router as Router4 } from "express";

// src/modules/reviwe/reviwe.service.ts
var createReview = async (payload, userId) => {
  const result = await prisma.review.create({
    data: {
      ...payload,
      studentId: userId
    },
    include: {
      tutor: true,
      student: true
    }
  });
  return result;
};
var showAllreviews = async () => {
  const result = await prisma.review.findMany({
    include: {
      tutor: true,
      student: true
    }
  });
  return result;
};
var showTutorReviews = async (tutorId) => {
  const result = await prisma.review.findMany({
    where: {
      tutorId
    },
    include: {
      tutor: true,
      student: true
    }
  });
  return result;
};
var reviewService = {
  createReview,
  showAllreviews,
  showTutorReviews
};

// src/modules/reviwe/review.controller.ts
var createReview2 = async (req, res) => {
  console.log("create review");
  try {
    const userId = req.user?.userId;
    const result = await reviewService.createReview(req.body, userId);
    return res.status(201).json(result);
  } catch (error) {
    console.error("Error creating review:", error);
  }
};
var showAllreviews2 = async (req, res) => {
  try {
    const result = await reviewService.showAllreviews();
    return res.status(200).json(result);
  } catch (error) {
    console.error("Error fetching reviews:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var showTutorReviews2 = async (req, res) => {
  try {
    const { userId } = req.user || {};
    const result = await reviewService.showTutorReviews(userId);
    return res.status(200).json({
      success: true,
      message: "Tutor reviews fetched successfully",
      data: result
    });
  } catch (error) {
    console.error("Error fetching tutor reviews:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var showTutorReviewsPublic = async (req, res) => {
  try {
    const { tutorId } = req.params;
    if (!tutorId) {
      return res.status(400).json({
        success: false,
        message: "tutorId is required"
      });
    }
    const result = await reviewService.showTutorReviews(tutorId);
    return res.status(200).json({
      success: true,
      message: "Tutor reviews fetched successfully",
      data: result
    });
  } catch (error) {
    console.error("Error fetching tutor reviews:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var reviewController = {
  createReview: createReview2,
  showAllreviews: showAllreviews2,
  showTutorReviews: showTutorReviews2,
  showTutorReviewsPublic
};

// src/modules/reviwe/review.route.ts
var router4 = Router4();
router4.post(
  "/",
  auth2("Student" /* Student */, "Tutor" /* Tutor */, "Admin" /* Admin */),
  reviewController.createReview
);
router4.get("/", reviewController.showAllreviews);
router4.get(
  "/tutor/reviews",
  auth2("Tutor" /* Tutor */),
  reviewController.showTutorReviews
);
router4.get("/tutor/:tutorId", reviewController.showTutorReviewsPublic);
var reviewRoute = router4;

// src/modules/admin/userManage/usermanage.route.ts
import { Router as Router5 } from "express";

// src/modules/admin/userManage/userManage.sevice.ts
var showAllUsers = async () => {
  const result = await prisma.user.findMany({
    include: {
      tutorProfile: true
      // bookingAsStudent:true,
      // bookingAsTutor: true,
    }
  });
  return result;
};
var deleteTutorProfile = async (userId) => {
  const result = await prisma.tutorProfile.delete({
    where: {
      userId
    }
  });
  return result;
};
var deleteUser = async (userId) => {
  const result = await prisma.user.delete({
    where: {
      id: userId
    }
  });
  return result;
};
var updateUserStatus = async (userId, status) => {
  const result = await prisma.user.update({
    where: { id: userId },
    data: { status }
  });
  return result;
};
var userManageService = {
  showAllUsers,
  deleteUser,
  updateUserStatus,
  deleteTutorProfile
};

// src/modules/admin/userManage/userManage.controllers.ts
var getAllUsers = async (req, res) => {
  try {
    const result = await userManageService.showAllUsers();
    return res.status(200).json({
      success: true,
      message: "All users fetched successfully",
      data: result
    });
  } catch (error) {
    console.error("Error fetching all users:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var deleteUser2 = async (req, res) => {
  try {
    const { userId } = req.params;
    const result = await userManageService.deleteUser(userId);
    return res.status(200).json({
      success: true,
      message: "User deleted successfully",
      data: result
    });
  } catch (error) {
    console.error("Error deleting user:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var updateUserStatus2 = async (req, res) => {
  try {
    const { userId } = req.params;
    const { status } = req.body;
    const result = await userManageService.updateUserStatus(
      userId,
      status
    );
    return res.status(200).json({
      success: true,
      message: "User status updated successfully",
      data: result
    });
  } catch (error) {
    console.error("Error updating user status:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var deleteTutorProfile2 = async (req, res) => {
  try {
    const { userId } = req.params;
    const result = await userManageService.deleteTutorProfile(userId);
    return res.status(200).json({
      success: true,
      message: "Tutor profile deleted successfully",
      data: result
    });
  } catch (error) {
    console.error("Error deleting tutor profile:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var userManageController = {
  getAllUsers,
  deleteUser: deleteUser2,
  updateUserStatus: updateUserStatus2,
  deleteTutorProfile: deleteTutorProfile2
};

// src/modules/admin/userManage/usermanage.route.ts
var router5 = Router5();
router5.get("/users", auth2("Admin" /* Admin */), userManageController.getAllUsers);
router5.put(
  "/users/:userId/status",
  auth2("Admin" /* Admin */),
  userManageController.updateUserStatus
);
router5.delete(
  "/users/:userId",
  auth2("Admin" /* Admin */),
  userManageController.deleteUser
);
router5.delete(
  "/users/:userId/tutor-profile",
  auth2("Admin" /* Admin */),
  userManageController.deleteTutorProfile
);
var userManageRouter = router5;

// src/modules/admin/bookingManage/bookingManageRouter.ts
import { Router as Router6 } from "express";

// src/modules/admin/bookingManage/bookingManageService.ts
var getAllBookings = async () => {
  const result = await prisma.booking.findMany({
    include: {
      student: true,
      tutor: true
    }
  });
  return result;
};
var removeCancelledBookings = async () => {
  const result = await prisma.booking.deleteMany({
    where: {
      status: BookingStatus.CANCELLED
    }
  });
  return result;
};
var bookingManageService = {
  getAllBookings,
  removeCancelledBookings
};

// src/modules/admin/bookingManage/bookingmanage.controller.ts
var getAllBookings2 = async (req, res) => {
  try {
    const result = await bookingManageService.getAllBookings();
    return res.status(200).json({
      success: true,
      message: "All bookings fetched successfully",
      data: result
    });
  } catch (error) {
    console.error("Error fetching all bookings:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var removeCancelledBookings2 = async (req, res) => {
  try {
    const result = await bookingManageService.removeCancelledBookings();
    return res.status(200).json({
      success: true,
      message: "Cancelled bookings removed successfully",
      data: result
    });
  } catch (error) {
    console.error("Error removing cancelled bookings:", error);
    return res.status(500).json({
      success: false,
      message: "Internal server error"
    });
  }
};
var bookingManageController = {
  getAllBookings: getAllBookings2,
  removeCancelledBookings: removeCancelledBookings2
};

// src/modules/admin/bookingManage/bookingManageRouter.ts
var router6 = Router6();
router6.get("/", bookingManageController.getAllBookings);
router6.delete(
  "/cancelled",
  auth2("Admin" /* Admin */),
  bookingManageController.removeCancelledBookings
);
var bookingManageRouter = router6;

// src/app.ts
var app = express();
var allowedOrigins = [
  process.env.APP_URL || "http://localhost:4000",
  process.env.PROD_APP_URL,
  // Production frontend URL
  "http://localhost:3000",
  "http://localhost:4000",
  "http://localhost:5000"
].filter(Boolean);
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      const isAllowed = allowedOrigins.includes(origin) || /^https:\/\/next-blog-client.*\.vercel\.app$/.test(origin) || /^https:\/\/.*\.vercel\.app$/.test(origin);
      if (isAllowed) {
        callback(null, true);
      } else {
        callback(new Error(`Origin ${origin} not allowed by CORS`));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
    exposedHeaders: ["Set-Cookie"]
  })
);
app.use(express.json());
app.get("/", (req, res) => {
  res.json({ message: "Tutor Booking API is running" });
});
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/tutors", tutorProfileRoute);
app.use("/api/categories", categoryRoute);
app.use("/api/bookings", bookingRoute);
app.use("/api/reviews", reviewRoute);
app.use("/admin", userManageRouter);
app.use("/api/admin/bookings", bookingManageRouter);
var app_default = app;
export {
  app_default as default
};
